### ISSUE TITLE
Invalid public key (zero) crashing oracle

### ISSUE THREAD

**Issue by ottosch** [setavenger/blindbit-oracle#16]
Transaction [d73f4a19f3973e90af6df62e735bb7b31f3d5ab8e7e26e7950651b436d093313](https://mempool.space/signet/tx/d73f4a19f3973e90af6df62e735bb7b31f3d5ab8e7e26e7950651b436d093313) is crashing the server on tweak.go, `sumPublicKeys`, due to paying to pubkey zero.

Edit: the input pubkeys have the same X, but opposite Y. Don't know if this could be the cause instead.

**Comment by setavenger** [comment]
Thanks for raising this. This transaction has led to a bit of trouble for other indexers as well. The issue is probably that the two inputs sum up to zero https://github.com/bitcoin/bitcoin/pull/28241#discussion_r1623063336

**Comment by setavenger** [comment]
should be fixed
