### ISSUE TITLE
Using `/tweaks` with a dust limit returns `null` instead of empty array

### ISSUE THREAD

**Issue by cygnet3** [setavenger/blindbit-oracle#21]
Requesting tweaks for block`214953` on Signet, when the block has no tweaks, gives me an empty array:

```sh
curl  'http://localhost:8000/tweaks/214953'

[]
```

However, when adding a dust limit (even just 1 sat), I get 'null' instead of an empty array:

```sh
curl 'http://localhost:8000/tweaks/214953?dustLimit=1'

null
```

For consistency, I would expect this to also return en empty array.

**Comment by setavenger** [comment]
Thanks for testing, fix is on dev now.
